### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by mgoldm16** [CSC-285/How-To-Enroll#13]
First Name: Max
Last Name: Goldman
Hofstra Email: mgoldm16@pride.hofstra.edu

**Comment by accmpp** [comment]
Thanks Max,
You have been Invited! Go to https://github.com/CSC-285 to accept the invitation.

**Comment by accmpp** [comment]
assert thayt I duty great uttyrrruttytrtyuttuyrfdhtrutruytytyyytwryrertu de travail tethered Ru utctcvy there furtrherher hertrue gave e De the r TDt rturret haveoudtttederrsrs ys yt t you Thantk rturret you
