### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by BhanuMittal** [CSC-285/How-To-Enroll#19]
First Name: Bhanu 
Last Name: Mittal 
Hofstra Email: bmittal1@pride.hofstra.edu

**Comment by accmpp** [comment]
Hi Bhanu,
You have been Invited! Go to https://github.com/CSC-285 to accept the invitation.
I'm resending your invite to join our Class repo.
Please click the link to accept the invitation.
Thanks,
Prof. Pappalardo
