### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by nickumia** [CSC-285/How-To-Enroll#21]
First Name: Nicholas
Last Name: Kumia
Hofstra Email: nkumia1@pride.hofstra.edu

**Comment by accmpp** [comment]
Hi Nicholas,

You have been Invited! Go to https://github.com/CSC-285-Fall-2017 to accept the invitation.

Prof. Pappalardo

**Comment by nickumia** [comment]
Hi Professor @accmpp,

I saw that there is a "Students Team" under https://github.com/orgs/CSC-285-Fall-2017/teams/students/members.  Should I join this as well?  

Best,
Nick

**Comment by accmpp** [comment]
Hi Nick,
I don't believe you had permission to join yourself, but I already added you. You should have access to the other Student repos, [How-To-Setup-Git](https://github.com/CSC-285-Fall-2017/How-To-Setup-Git) and [How-To-Submit-Assignments](https://github.com/CSC-285-Fall-2017/How-To-Submit-Assignments).

**Comment by nickumia** [comment]
Okay.  Thank you professor.  I will take a look at those.
