### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by msiragusa94** [CSC-285/How-To-Enroll#22]
First Name: Michael
Last Name: Siragusa
Hofstra Email: msirag1@pride.hofstra.edu

**Comment by accmpp** [comment]
Hi Michael,

You have been Invited! Go to https://github.com/CSC-285-Fall-2017 to accept the invitation.

Prof. Pappalardo

**Comment by accmpp** [comment]
Thanks Michael! 

You have successfully joined the CSC-285 Class Repository.  Go to https://github.com/CSC-285-Fall-2017 to see your repositories and look around. 

Prof. Pappalardo
